### ISSUE TITLE
Release job failed: `BUF_TOKEN` is not valid

### ISSUE THREAD

**Issue by mbrobbel** [substrait-io/substrait#531]
It seem that [the release job failed](https://github.com/substrait-io/substrait/actions/runs/5634052162)

https://github.com/substrait-io/substrait/actions/runs/5634052162/job/15263584229#step:6:84
```
[2:33:44 AM] [semantic-release] [@semantic-release/exec] › ℹ  Call script ci/release/prepare.sh
Failure: the BUF_TOKEN environment variable is set, but is not valid. Set BUF_TOKEN to a valid Buf API key, or unset it. For details, visit https://docs.buf.build/bsr/authentication
[2:33:44 AM] [semantic-release] › ✘  Failed step "prepare" of plugin "@semantic-release/exec"
[2:33:44 AM] [semantic-release] › ✘  An error occurred while running semantic-release: Error: Command failed with exit code 1: ci/release/prepare.sh
Failure: the BUF_TOKEN environment variable is set, but is not valid. Set BUF_TOKEN to a valid Buf API key, or unset it. For details, visit https://docs.buf.build/bsr/authentication
    at makeError (/home/runner/.npm/_npx/9dfb008ba7dcc360/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/home/runner/.npm/_npx/9dfb008ba7dcc360/node_modules/execa/index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async module.exports (/home/runner/.npm/_npx/9dfb008ba7dcc360/node_modules/@semantic-release/exec/lib/exec.js:16:11)
    at async prepare (/home/runner/.npm/_npx/9dfb008ba7dcc360/node_modules/@semantic-release/exec/index.js:54:5)
    at async validator (file:///home/runner/.npm/_npx/9dfb008ba7dcc360/node_modules/semantic-release/lib/plugins/normalize.js:36:24)
    at async file:///home/runner/.npm/_npx/9dfb008ba7dcc360/node_modules/semantic-release/lib/plugins/pipeline.js:38:36
    at async Promise.all (index 0)
    at async next (file:///home/runner/.npm/_npx/9dfb008ba7dcc360/node_modules/semantic-release/node_modules/p-reduce/index.js:15:44) {
  shortMessage: 'Command failed with exit code 1: ci/release/prepare.sh',
  command: 'ci/release/prepare.sh',
  escapedCommand: '"ci/release/prepare.sh"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'Failure: the BUF_TOKEN environment variable is set, but is not valid. Set BUF_TOKEN to a valid Buf API key, or unset it. For details, visit https://docs.buf.build/bsr/authentication',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  pluginName: '@semantic-release/exec'
}
Error: Command failed with exit code 1: ci/release/prepare.sh
Failure: the BUF_TOKEN environment variable is set, but is not valid. Set BUF_TOKEN to a valid Buf API key, or unset it. For details, visit https://docs.buf.build/bsr/authentication
    at makeError (/home/runner/.npm/_npx/9dfb008ba7dcc360/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/home/runner/.npm/_npx/9dfb008ba7dcc360/node_modules/execa/index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async module.exports (/home/runner/.npm/_npx/9dfb008ba7dcc360/node_modules/@semantic-release/exec/lib/exec.js:16:11)
    at async prepare (/home/runner/.npm/_npx/9dfb008ba7dcc360/node_modules/@semantic-release/exec/index.js:54:5)
    at async validator (file:///home/runner/.npm/_npx/9dfb008ba7dcc360/node_modules/semantic-release/lib/plugins/normalize.js:36:24)
    at async file:///home/runner/.npm/_npx/9dfb008ba7dcc360/node_modules/semantic-release/lib/plugins/pipeline.js:38:36
    at async Promise.all (index 0)
    at async next (file:///home/runner/.npm/_npx/9dfb008ba7dcc360/node_modules/semantic-release/node_modules/p-reduce/index.js:15:44) {
  shortMessage: 'Command failed with exit code 1: ci/release/prepare.sh',
  command: 'ci/release/prepare.sh',
  escapedCommand: '"ci/release/prepare.sh"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'Failure: the BUF_TOKEN environment variable is set, but is not valid. Set BUF_TOKEN to a valid Buf API key, or unset it. For details, visit https://docs.buf.build/bsr/authentication',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  pluginName: '@semantic-release/exec'
}
Error: Process completed with exit code 1.
```

**Comment by jacques-n** [comment]
I believe this has been fixed. Feel free to reopen if I'm incorrect.

**Comment by mbrobbel** [comment]
This is happening again: https://github.com/substrait-io/substrait/actions/runs/10650383058/job/29521684578#step:6:163

**Comment by jacques-n** [comment]
Think I fixed again.
